### PR TITLE
Adding Django 3 support

### PR DESCRIPTION
**Pull request by adamcharnock**
As per #676, I've gone ahead and brought all dependencies up to date and got all tests passing. Note:

* Running against Django 3.1.5
* Fixed various warnings
* Now using Django's internal JSONField
* Removed all Python 2 compatibility imports, which are largely gone from Django 3 anyway
* I managed my own environment using poetry, but I haven't committed those files. I've updated the various requirements files with the new versions, so CI *should* pass.

I'm sorry that this this is a big PR, but I don't really think there a practical way to do this incrementally. I've tried to make every commit pretty stand-alone though, so you should be able to walk through the individual commits and see what is going on. It's mostly very simple changes over a large number of files.

### CODE REVIEW

**Comment by adamcharnock** [comment]
It looks like the generic (not postgres-specific) `JSONField` is only in Django 3. So it looks like keeping Django <3 support is going to require keeping a third-party JSON field library in the requirements.

So, forgive me for asking, but is there any appetite for doing a major (backwards-compatible) release which drops support Django < 3, and older Python versions too?

**Comment by bogdanpetrea** [comment]
> It looks like the generic (not postgres-specific) `JSONField` is only in Django 3. So it looks like keeping Django <3 support is going to require keeping a third-party JSON field library in the requirements.
> 
> So, forgive me for asking, but is there any appetite for doing a major (backwards-compatible) release which drops support Django < 3, and older Python versions too?

No, Django > 3 and Python >= 3.6 should be the way to go forward. I'm only concerned about migrating existing data from the third-party JSONField to the Django in-built one.

**Comment by bogdanpetrea** [comment]
Hey @adamcharnock , I've changed our Drone config and the Travis one to use Django>3 and Python>3.6. Please rebase your PR branch onto master.

**Comment by adamcharnock** [comment]
@bogdanpetrea Rebase done

**Comment by bogdanpetrea** [comment]
Included and merged in a separate PR (https://github.com/silverapp/silver/pull/680). Thanks again!

**Pull request closed without merging**
